In [3]:
# 初始化 Tensor

In [4]:
import torch
import numpy as np

In [5]:
# 从array初始化
a = [[1,2,3],[2,3,4]]
a_tensor = torch.tensor(a)
print(a_tensor, type(a_tensor))

tensor([[1, 2, 3],
        [2, 3, 4]]) <class 'torch.Tensor'>


In [6]:
# 从numpy array初始化
b = np.array(a)
b_tensor = torch.from_numpy(b)
print(b_tensor, type(b_tensor))

tensor([[1, 2, 3],
        [2, 3, 4]]) <class 'torch.Tensor'>


In [7]:
# 从其他的tensor初始化
ones = torch.ones_like(b_tensor)
rand = torch.rand_like(b_tensor, dtype=torch.float)
print(ones)
print(rand)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.5393, 0.9448, 0.0266],
        [0.8782, 0.3296, 0.9215]])


In [8]:
# 随机或常数值初始化
shape = (2,3,) # 元组，一般需要最后面的一个逗号
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print('rand_tensor\n',rand_tensor)
print('ones_tensor\n',ones_tensor)
print('zeros_tensor\n',zeros_tensor)

rand_tensor
 tensor([[0.6547, 0.8275, 0.2216],
        [0.1751, 0.8509, 0.7113]])
ones_tensor
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor的属性
+ shape,维度
+ dtype,数据类型
+ device,存储设备(CPU | GPU)

In [9]:
print('shape:',rand_tensor.shape)
print('dtype',rand_tensor.dtype)
print('device',rand_tensor.device)

shape: torch.Size([2, 3])
dtype torch.float32
device cpu


## 对tensor的基础操作

1. 将tensor的存储设备转移(tensor.to)
2. 矩阵或向量见的点乘或者叉乘(matmul,@,...)
3. 标准的切片或者与numpy数组类似的操作([:,:])
4. 连接操作(torch.cat)
5. 单元素tensor
6. tensor就地操作


In [16]:
# 1. 设备转移
shape = (3,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')
    print(rand_tensor.device)

tensor([[0.3407, 0.9878, 0.3957],
        [0.1146, 0.4986, 0.3649],
        [0.5112, 0.3408, 0.1508]])
cuda:0


In [22]:
# 2. 连接矩阵的操作,dim在-2到1之间
penta_tensor = torch.cat([rand_tensor,rand_tensor,rand_tensor], dim=1)
print(penta_tensor)

tensor([[0.3407, 0.9878, 0.3957, 0.3407, 0.9878, 0.3957, 0.3407, 0.9878, 0.3957],
        [0.1146, 0.4986, 0.3649, 0.1146, 0.4986, 0.3649, 0.1146, 0.4986, 0.3649],
        [0.5112, 0.3408, 0.1508, 0.5112, 0.3408, 0.1508, 0.5112, 0.3408, 0.1508]],
       device='cuda:0')


In [23]:
# 3. 基本的切片操作
print("第一行:",penta_tensor[0,:])
print('第一列:',penta_tensor[:,0])
print('最后一列:',penta_tensor[...,-1])

第一行: tensor([0.3407, 0.9878, 0.3957, 0.3407, 0.9878, 0.3957, 0.3407, 0.9878, 0.3957],
       device='cuda:0')
第一列: tensor([0.3407, 0.1146, 0.5112], device='cuda:0')
最后一列: tensor([0.3957, 0.3649, 0.1508], device='cuda:0')


In [39]:
# 4. 矩阵计算，点乘表示的是标量求积，对应位置的数字相乘并求和，叉乘表示的是向量求乘积，最终得到的是与相乘的向量垂直的一个向量
shape = (2,2,)
x1 = torch.rand(shape)
x2 = torch.rand_like(x1)
## 叉乘
y1 = x1 @ x2
y2 = torch.matmul(x1, x2)
y3 = torch.rand_like(x1)
torch.matmul(x1,x2,out=y3)
print(y1)
print(y2)
print(y3)

## 点乘
y4 = x1 * x2
y5 = torch.mul(x1, x2)
y6 = torch.rand_like(x1)
torch.mul(x1, x2, out = y6)
print(y4)
print(y5)
print(y6)

# 以下代码用来测试点乘叉乘
array_one = torch.tensor([1,2,3])  # 向量叉乘无需转制，是按照正确的方法相乘 即 |a| * |b| * sinθ
array_two = torch.tensor([2,3,4])
print(array_one @ array_two.T)
print(array_one * array_two)

tensor([[0.5272, 0.6585],
        [0.6543, 0.8486]])
tensor([[0.5272, 0.6585],
        [0.6543, 0.8486]])
tensor([[0.5272, 0.6585],
        [0.6543, 0.8486]])
tensor([[0.2910, 0.3010],
        [0.2145, 0.5752]])
tensor([[0.2910, 0.3010],
        [0.2145, 0.5752]])
tensor([[0.2910, 0.3010],
        [0.2145, 0.5752]])
tensor(20)
tensor([ 2,  6, 12])


In [41]:
# 5. 单元素tensor,使用item获取元素的值
sum = y5.sum()
sum_value = sum.item()
print(type(sum), sum)
print(type(sum_value), sum_value)

<class 'torch.Tensor'> tensor(1.3817)
<class 'float'> 1.3817049264907837


In [43]:
# 6. 就地操作，一般都是在非就地操作的基础上加一个 `_`后缀
y5.add_(1)
print(y5)

tensor([[1.2910, 1.3010],
        [1.2145, 1.5752]])


## tensor与numpy是一对亲兄弟
他们之间存在着不可磨灭的联系，在某些底层，其实这两个结构可能存储在一个设备地址上。所以，如果基于numpy创建的tensor，修改其中一个，另外一个也会受到影响而修改。


In [48]:
array = np.array([[1,2,3], [2, 3, 4]])
tensor_array = torch.from_numpy(array)
print(array)
print(tensor_array)

# 修改numpy数组
array[0,1] = 10
print('影响后的tensor:',tensor_array)

# 修改tensor
tensor_array.add_(10)
print('影响后的numpy', array)

[[1 2 3]
 [2 3 4]]
tensor([[1, 2, 3],
        [2, 3, 4]])
影响后的tensor: tensor([[ 1, 10,  3],
        [ 2,  3,  4]])
影响后的numpy [[11 20 13]
 [12 13 14]]


OVER~