In [2]:
import torch
import numpy as np

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [6]:
array = np.ndarray(shape=(3,3))
print(array)
tensor = torch.from_numpy(array)
print(tensor.device)
tensor = tensor.to(device)
print(tensor.device)

[[4.44580900e-316 0.00000000e+000 2.12199582e-314]
 [2.12199579e-314 4.44591651e-316 2.03413862e-316]
 [0.00000000e+000 4.43204868e-316 1.90979622e-313]]
cpu
cuda:0


In [5]:
print(torch.version.cuda)

10.2
